# Generated by Django 3.2.5 on 2026-09-03 20:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_mode', models.BooleanField(default=False)),
                ('num_bands', models.IntegerField(default=0)),
                ('first_app_position', models.FloatField(default=0.0)),
                ('edge_cut', models.FloatField(default=0.0)),
                ('migration_front', models.FloatField(default=0.0)),
                ('band_spacing', models.FloatField(default=30.0)),
                ('band_width', models.FloatField(default=1.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='rtlc.uploadedimage')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('file', models.ImageField(upload_to='extracted_bands/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='rtlc.uploadedimage')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask_file', models.FileField(upload_to='masks/%Y/%m/%d/')),
                ('mask_height', models.IntegerField()),
                ('mask_width', models.IntegerField()),
                ('rectangle_centers_x', models.JSONField(default=list)),
                ('rectangle_width', models.FloatField(default=1.0)),
                ('global_top_y', models.FloatField(default=0.0)),
                ('global_bottom_y', models.FloatField(default=0.0)),
                ('consistent_group_spacing', models.FloatField(blank=True, null=True)),
                ('raw_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='rtlc.uploadedimage')),
            ],
        ),
    ]
