#version: "3"

services:   
  redis:
    restart: always
    container_name: oc_redis_cont
    image: redis:latest
    command: redis-server
    ports:
      - '6379:6379'

  app:
    restart: always
    container_name: oc_manager_cont
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - UDEV=1
      - DJANGO_SETTINGS_MODULE=app.settings
      - QT_X11_NO_MITSHM=1
      - DISPLAY=$DISPLAY
    expose:
      - "8000"
    privileged: true
    volumes:
      - ./app:/app
      - /dev:/dev
      - /run/udev:/run/udev:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
    cap_add:
      - SYS_ADMIN
    devices:
      - '/dev:/dev'
    tmpfs:
      - '/dev/shm:exec'
    command: >
      sh -c " python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"

  nextjs:
    build: ./frontend
    container_name: oc_nextjs_cont
    expose:
    - "3000"
    # ports:
    #   - "3000:3000"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend/dashboard:/dashboard
      - /dashboard/node_modules
      - /dashboard/.next
    depends_on:
      - app
    command: npm run dev



  nginx:
    image: nginx:latest
    container_name: oc_nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - app
      - nextjs
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
